### PR TITLE
GH-11: Adjusted the lookup to the latest VS Code.

### LINKED ISSUE #11: Could not find Git on the PATH - not recognized on windows
Message: "Could not find Git on the PATH"

OS - Windows 10 Pro
---
Git binaries on path:
C:\Users\<user>\AppData\Local\Programs\Git\bin

Using git Bash:
which
/mingw64/bin/git

### PR DESCRIPTION
**Pull request by kittaakos**
- [win32]: Use `which` when cannot find Git on the `$PATH`.
 - Listen on the process' `close` instead of `exit`.
 - Moved the Windows build to Travis.
 - Pinned the versions with `yarn.lock`.
 - Bumped up the dependencies.
 - New version -> `0.0.2`.

Closes #11.

Co-authored-by: Alex Tugarev <alex.tugarev@typefox.io>
Co-authored-by: Akos Kitta <kittaakos@typefox.io>

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by mcgordonite** [comment]
Thanks @kittaakos! On my machine with a single-user git install, `yarn test` succeeds on my machine in git bash, powershell and cmd, finding git from the path.

It also works on my machine with an all-user git install in Program Files.

**Comment by kittaakos** [comment]
Thanks for the help, @mcgordonite! 🥇
I'll publish a new release tomorrow.

@AlexTugarev, can you please briefly look into the code? The changeset is based on VS Code. The ref is [here](https://github.com/microsoft/vscode/blob/master/extensions/git/src/git.ts#L50-L141).

**Comment by AlexTugarev** [comment]
Will look into it shortly.

**Comment by AlexTugarev** [comment]
@kittaakos I started testing this PR and saw some weird behavior with `execPath` computation. It does ring a bell, as there are rare git finding errors in Gitpod, which I didn't understand, but it might be connected to `execPath`.

What I mean is, on the first try I got `"execPath":"."`, but the following retries were good. I started new Gitpod workspace, build again, tried again, and it was good. I thought it was a glitch, but then I repeated quite often and hit it again. See:

```
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))
Promise {
  <pending>,...
> {"path":"/usr/bin/git","version":"2.20.1","execPath":"/usr/lib/git-core"}
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))
Promise {
  <pending>,...
> {"path":"/usr/bin/git","version":"2.20.1","execPath":"/usr/lib/git-core"}
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))
Promise {
  <pending>,...
> {"path":"/usr/bin/git","version":"2.20.1","execPath":"/usr/lib/git-core"}
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))
Promise {
  <pending>,...
> {"path":"/usr/bin/git","version":"2.20.1","execPath":"."}
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))
```

I just did `cd lib` and ran `node` to try it out. `/usr/lib/git-core` should be returned as `execPath`, but last call doesn't.

**Comment by kittaakos** [comment]
> on the first try I got `"execPath":"."`

How can I reproduce it?

**Comment by AlexTugarev** [comment]
> require('./find-git-exec').default().then(git => console.log(JSON.stringify(git)))

**Comment by kittaakos** [comment]
Long story short, running the same test 5k times results in an error, I can see an `EAGAIN` error when running `git --version` and `git --exec-path` in parallel.

This PR is on hold.

**Comment by AlexTugarev** [comment]
@kittaakos after some more testing on linux, in a Gitpod workspace to be more specific, @geropl and I found that `child_process.exec`/`child_process.execFile` continues to work nicely while `child_process.spawn` starts omitting `stdout`, and worse it seem like there is a limit of ~512 child processes to node that can actually run "at the same time".

@geropl pointed out, `execFile` need less resources, so it would be nice to use it everywhere where only (short) stdout is needed, but we don't care about the interaction and process mgmt.
I used the following code in a test bench creating 1000 promises in a loop:
```
const getExecPath = async (gitPath) => {
    return new Promise((resolve, reject) => {
        cp.execFile(`${gitPath}`, ["--exec-path"], (error, stdout, stderr) => {
            if (error) {
                reject(new Error(`Git not found under '${gitPath}'.`))
            } else {
                resolve(stdout.trim())
            }
        })
    })
}
```

**Comment by AlexTugarev** [comment]
@kittaakos, if you are super busy, would you like to receive a PR against this one?

**Comment by kittaakos** [comment]
> `execFile`

I wanted to keep the implementation in-sync with VS Code 😕.

**Comment by AlexTugarev** [comment]
> I wanted to keep the implementation in-sync with VS Code 😕.

at some point, they will learn it as well ;-)

**Comment by kittaakos** [comment]
> receive a PR against this one?

Please, I can still see `EAGAIN` error with `execFile` as well.

**Comment by AlexTugarev** [comment]
> Please, I can still see EAGAIN error with execFile as well.

that is, when you reach the limit of file descriptors. on my local machine this happens with +1.5k simultaneously spawned child processes. but it should work nicely in the range of 511 and 1000.

**Comment by kittaakos** [comment]
> 511 and 1000.

Crazy but true. I tried to run the tests 5k times, it failed. It passes with 500.

**Comment by AlexTugarev** [comment]
it should have worked with 511 before ;-) that's the magic number. child number 512 won't have a readable state, i.e. no stdout.

**Comment by kittaakos** [comment]
To sum up:
 - there is a limit on how many `git` commands can be executed, hence we run the tests 500 times.
 - we are aware of issues but this PR was intended to fix the Windows issue anyways.

I am going to publish a new version.

**Comment by kittaakos** [comment]
> Verified this works on local OSX and in Gitpod (docker/linux environment)

Thank you for your help, @AlexTugarev!

**Pull request merged**
